Repository Megalotron/go-flowmeter, pull requests merged in 2022-06, with the labels that each got.

#1 Add minimal go project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/ci.yaml
  .gitignore
  go.mod
  main.go
Labels: enhancement

#3 Add PCAP packet encapsulation
  capsule/packet.go
  capsule/packet_test.go
  capsule/protocol_number.go
Labels: enhancement

#4 Add PCAP file reader
  .github/workflows/ci.yaml
  README.md
  capsule/packet.go
  capsule/packet_test.go
  capsule/pcap_reader.go
  capsule/pcap_reader_test.go
  go.mod
  go.sum
  tests/test_ethernet.pcap
Labels: enhancement

#6 ci(build-image): Add Dockerfile and CI
  .github/workflows/ci.yaml
  Dockerfile
Labels: area/ci

#7 ci(push-image): Add auto-releaser for Docker image
  .github/workflows/releaser.yaml
Labels: enhancement, docker
